name: news_app
description: A modern news application with category-based news fetching

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  connectivity_plus: ^6.0.5

  http: ^1.3.0
  cached_network_image: ^3.2.3
  webview_flutter: ^4.0.7
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0  # For custom typography
  flutter_svg: ^2.0.9   # For SVG icons (optional)
  shimmer: ^3.0.0       # For loading effects (optional)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/header_image.png

  # Optional: Add font configurations if needed
fonts:
     - family: Schyler
       fonts:
         - asset: fonts/Schyler-Regular.ttf